const nationalities : {code : string, name: string}[] = [
    { code: "UK" , name: "United Kingdom" },
    { code: "US" , name: "United States" },
    { code: "CA" , name: "Canada" },
    { code: "AU" , name: "Australia" },
    { code: "IN" , name: "India" },
    { code: "DE" , name: "Germany" },
    { code: "FR" , name: "France" },
    { code: "JP" , name: "Japan" },
    { code: "CN" , name: "China" },
    { code: "NG" , name: "Nigeria" },
    { code: "BR" , name: "Brazil" },
    { code: "ZA" , name: "South Africa" },
    { code: "MX" , name: "Mexico" },
    { code: "RU" , name: "Russia" },
    { code: "IT" , name: "Italy" },
    { code: "ES" , name: "Spain" },
    { code: "KR" , name: "South Korea" },
    { code: "SE" , name: "Sweden" },
    { code: "NL" , name: "Netherlands" },
    { code: "CH" , name: "Switzerland" },
]
export default nationalities;